### ISSUE TITLE
Inconsistent translation of `(::Type{..})` constructors

### ISSUE THREAD

**Issue by mauro3** [JuliaComputing/FemtoCleaner.jl#44]
`(::Type{MT6{R,I}}){R,I}(r) = new{R,I}(r,r)` like expressions are sometimes translated to `MT6{R,I}(r) where {R,I} = new{R,I}(r,r)` but sometimes not.  See: https://github.com/mauro3/Parameters.jl/pull/40/files/f03f7e350ece56cd57b6243f770281abe40629e3#r140249577

(note that somehow I didn't get the `bad bot` to run, so I filed this issue by hand.)

**Comment by Keno** [comment]
Finally took a look at this. A bunch of these were disabled because they were inside unknown macros. We conservatively disabled most fixes inside unknown macros, because we can't know whether things make a difference. If you want you can add your macros to the known exceptions list, in Deprecations.jl.
